package com.example.weatherapp.domain.models.entity

data class CurrentResponseEntity(
    val lastUpdatedEpoch: Double,
    val lastUpdated: String,
    val tempC: Double,
    val tempF: Double,
    val isDay: Double,
    val condition: ConditionResponseEntity,
    val windMph: Double,
    val windKph: Double,
    val windDegree: Double,
    val windDir: String,
    val pressureMb: Double,
    val pressureIn: Double,
    val precipMm: Double,
    val precipIn: Double,
    val humidity: Double,
    val cloud: Double,
    val feelsLikeC: Double,
    val feelsLikeF: Double,
    val windchillC: Double,
    val windchillF: Double,
    val heatIndexC: Double,
    val heatIndexF: Double,
    val dewPointC: Double,
    val dewPointF: Double,
    val visKm: Double,
    val visMiles: Double,
    val uv: Double,
    val gustMph: Double,
    val gustKph: Double,
)
