package com.example.weatherapp.domain.models.entity

data class HourResponseEntity(
    val timeEpoch: Double,
    val time: String,
    val tempC: Double,
    val tempF: Double,
    val isDay: Double,
    val condition: ConditionResponseEntity,
    val windMph: Double,
    val windKph: Double,
    val windDegree: Double,
    val windDir: String,
    val pressureMb: Double,
    val pressureIn: Double,
    val precipMm: Double,
    val precipIn: Double,
    val snowCm: Double,
    val humidity: Double,
    val cloud: Double,
    val feelsLikeC: Double,
    val feelsLikeF: Double,
    val windchillC: Double,
    val windchillF: Double,
    val heatIndexC: Double,
    val heatIndexF: Double,
    val dewPointC: Double,
    val dewPointF: Double,
    val willItRain: Double,
    val chanceOfRain: Double,
    val willItSnow: Double,
    val chanceOfSnow: Double,
    val visKm: Double,
    val visMiles: Double,
    val gustMph: Double,
    val gustKph: Double,
    val uv: Double,
)
