package com.example.weatherapp.builder

import com.example.weatherapp.data.network.models.response.dto.ConditionResponseDto
import com.example.weatherapp.data.network.models.response.dto.CurrentResponseDto
import com.example.weatherapp.data.network.models.response.dto.mapToDomain
import com.example.weatherapp.domain.models.entity.CurrentResponseEntity

data class CurrentResponseTestBuilder(
    val lastUpdatedEpoch: Double = 1636121234.0,
    val lastUpdated: String = "2021-11-04 10:00",
    val tempC: Double = 18.0,
    val tempF: Double = 64.4,
    val isDay: Double = 1.0,
    val condition: ConditionResponseDto= ConditionResponseTestBuilder().buildToDto(),
    val windMph: Double = 5.0,
    val windKph: Double = 8.0,
    val windDegree: Double = 270.0,
    val windDir: String = "W",
    val pressureMb: Double = 1012.0,
    val pressureIn: Double = 30.4,
    val precipMm: Double = 0.0,
    val precipIn: Double = 0.0,
    val humidity: Double = 50.0,
    val cloud: Double = 0.0,
    val feelsLikeC: Double = 18.0,
    val feelsLikeF: Double = 64.4,
    val windchillC: Double = 18.0,
    val windchillF: Double = 64.4,
    val heatIndexC: Double = 18.0,
    val heatIndexF: Double = 64.4,
    val dewPointC: Double = 10.0,
    val dewPointF: Double = 50.0,
    val visKm: Double = 10.0,
    val visMiles: Double = 6.0,
    val uv: Double = 5.0,
    val gustMph: Double = 6.0,
    val gustKph: Double = 9.7
) {
    fun build() = CurrentResponseEntity(
        lastUpdatedEpoch,
        lastUpdated,
        tempC,
        tempF,
        isDay,
        condition.mapToDomain(),
        windMph,
        windKph,
        windDegree,
        windDir,
        pressureMb,
        pressureIn,
        precipMm,
        precipIn,
        humidity,
        cloud,
        feelsLikeC,
        feelsLikeF,
        windchillC,
        windchillF,
        heatIndexC,
        heatIndexF,
        dewPointC,
        dewPointF,
        visKm,
        visMiles,
        uv,
        gustMph,
        gustKph
    )

    fun buildToDto() = CurrentResponseDto(
        lastUpdatedEpoch,
        lastUpdated,
        tempC,
        tempF,
        isDay,
        condition,
        windMph,
        windKph,
        windDegree,
        windDir,
        pressureMb,
        pressureIn,
        precipMm,
        precipIn,
        humidity,
        cloud,
        feelsLikeC,
        feelsLikeF,
        windchillC,
        windchillF,
        heatIndexC,
        heatIndexF,
        dewPointC,
        dewPointF,
        visKm,
        visMiles,
        uv,
        gustMph,
        gustKph
    )
}