package com.example.weatherapp.builder

import com.example.weatherapp.domain.models.entity.ConditionResponseEntity
import com.example.weatherapp.domain.models.entity.HourResponseEntity
import kotlin.Double

data class HourResponseTestBuilder(
    val timeEpoch: Double = 0.0,
    val time: String = "",
    val tempC: Double = 0.0,
    val tempF: Double = 0.0,
    val isDay: Double = 0.0,
    val condition: ConditionResponseEntity = ConditionResponseTestBuilder().build(),
    val windMph: Double = 0.0,
    val windKph: Double = 0.0,
    val windDegree: Double = 0.0,
    val windDir: String = "",
    val pressureMb: Double = 0.0,
    val pressureIn: Double = 0.0,
    val precipMm: Double = 0.0,
    val precipIn: Double = 0.0,
    val snowCm: Double = 0.0,
    val humidity: Double = 0.0,
    val cloud: Double = 0.0,
    val feelsLikeC: Double = 0.0,
    val feelsLikeF: Double = 0.0,
    val windchillC: Double = 0.0,
    val windchillF: Double = 0.0,
    val heatIndexC: Double = 0.0,
    val heatIndexF: Double = 0.0,
    val dewPointC: Double = 0.0,
    val dewPointF: Double = 0.0,
    val willItRain: Double = 0.0,
    val chanceOfRain: Double = 0.0,
    val willItSnow: Double = 0.0,
    val chanceOfSnow: Double = 0.0,
    val visKm: Double = 0.0,
    val visMiles: Double = 0.0,
    val gustMph: Double = 0.0,
    val gustKph: Double = 0.0,
    val uv: Double = 0.0,

    ) {
    fun build() = HourResponseEntity(
        timeEpoch,
        time,
        tempC,
        tempF,
        isDay,
        condition,
        windMph,
        windKph,
        windDegree,
        windDir,
        pressureMb,
        pressureIn,
        precipMm,
        precipIn,
        snowCm,
        humidity,
        cloud,
        feelsLikeC,
        feelsLikeF,
        windchillC,
        windchillF,
        heatIndexC,
        heatIndexF,
        dewPointC,
        dewPointF,
        willItRain,
        chanceOfRain,
        willItSnow,
        chanceOfSnow,
        visKm,
        visMiles,
        gustMph,
        gustKph,
        uv,
    )
}